### ISSUE TITLE
OSError: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by qin1114** [WonderLandxD/sdpc-for-python#12]
I tried to install on my linux system and found error:
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/qinmenghan/miniconda3/envs/clam/lib/python3.7/site-packages/sdpc/LINUX/libDecodeSdpc.so)

Total error information:
Traceback (most recent call last):
  File "/home/qinmenghan/Pathology/code/test_openslide.py", line 1, in <module>
    import sdpc
  File "/home/qinmenghan/miniconda3/envs/clam/lib/python3.7/site-packages/sdpc/__init__.py", line 1, in <module>
    from sdpc.Sdpc import Sdpc
  File "/home/qinmenghan/miniconda3/envs/clam/lib/python3.7/site-packages/sdpc/Sdpc.py", line 24, in <module>
    so = ctypes.CDLL(soPath)
  File "/home/qinmenghan/miniconda3/envs/clam/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/qinmenghan/miniconda3/envs/clam/lib/python3.7/site-packages/sdpc/LINUX/libDecodeSdpc.so)

It is impossible to update GLIBC which will cause a lot of trouble, I wonder what can I do?

**Comment by WonderLandxD** [comment]
Maybe you can install the sdpc with a higher python version of conda, e.g. python 3.11.4

**Comment by qin1114** [comment]
Thank you for your reply!
I've tried to create a new conda environment <sdpc> with python 3.11.2, but the error still exists

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qinmenghan/miniconda3/envs/sdpc/lib/python3.11/site-packages/sdpc/__init__.py", line 1, in <module>
    from sdpc.Sdpc import Sdpc
  File "/home/qinmenghan/miniconda3/envs/sdpc/lib/python3.11/site-packages/sdpc/Sdpc.py", line 37, in <module>
    so = ctypes.CDLL(soPath)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/qinmenghan/miniconda3/envs/sdpc/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/qinmenghan/miniconda3/envs/sdpc/lib/python3.11/site-packages/sdpc/LINUX/libDecodeSdpc.so)

maybe there are something wrong with GLIBC version compatibility, my GLIBC version list with command "strings /lib/x86_64-linux-gnu/libc.so.6 |grep GLIBC_":
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_2.29
GLIBC_2.30
GLIBC_PRIVATE

**Comment by WonderLandxD** [comment]
You can try to use the old version of the compiled file, here is the download link:
[https://cloud.tsinghua.edu.cn/f/ff9288a0533d489584da/?dl=1](url)
This requires you to replace all the files in the LINUX folder of sdpc library, which may help you.

**Comment by qin1114** [comment]
Thank you very much for your reply! This has truly solved my problem perfectly!
