### ISSUE TITLE
OSError: XXXXXXX: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HaiyuGong** [WonderLandxD/sdpc-for-python#14]
Hi, 
Thank you very much for developing the Python module for processing whole slide images (WSIs) in **.sdpc** format.
When I run `import sdpc`, I encountered the following error:
```bash
OSError: libjpeg.so.8: cannot open shared object file: No such file or directory
```
I followed the instructions in Issues 2, and found `libjpeg.so.8` in the directory `/usr/local/miniconda3/lib/python3.8/site-packages/sdpc/LINUX/jpeg/`. So, I add the following code in the last line of `~/.bashrc`, and ran `source ~/.bashrc`. The 2 other pathes were added in case of other similar errors.
```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/miniconda3/lib/python3.8/site-packages/sdpc/LINUX/:/usr/local/miniconda3/lib/python3.8/site-packages/sdpc/LINUX/jpeg/:/usr/local/miniconda3/lib/python3.8/site-packages/sdpc/LINUX/ffmpeg/
```
But, I encountered another similar error: 
```bash
OSError: libnuma.so.1: cannot open shared object file: No such file or directory
```
I didn't find `libnuma.so.1` in the folder named `sdpc`.

**Comment by WonderLandxD** [comment]
Hi,
maybe you can try to use the old version of the compiled file to see if it works.
 [https://cloud.tsinghua.edu.cn/f/ff9288a0533d489584da/?dl=1](https://github.com/WonderLandxD/sdpc-for-python/issues/url)
This requires you to replace all the files in the LINUX folder of sdpc library. (#12)

**Comment by qin1114** [comment]
Hi,
I've replace all the files in the LINX folder of sdpc library, but still found error when import sdpc:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/__init__.py", line 1, in <module>
    from sdpc.Sdpc import Sdpc
  File "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/Sdpc.py", line 37, in <module>
    so = ctypes.CDLL(soPath)
  File "/root/miniconda/envs/clam/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libDecodeHevc.so: cannot open shared object file: No such file or directory

I find libDecodeHevc.so file in "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/LINUX/libDecodeHevc.so", but I don't know why the system can't find file.

**Comment by AIzealotwu** [comment]
> Hi, I've replace all the files in the LINX folder of sdpc library, but still found error when import sdpc: Traceback (most recent call last): File "", line 1, in File "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/**init**.py", line 1, in from sdpc.Sdpc import Sdpc File "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/Sdpc.py", line 37, in so = ctypes.CDLL(soPath) File "/root/miniconda/envs/clam/lib/python3.7/ctypes/**init**.py", line 364, in **init** self._handle = _dlopen(self._name, mode) OSError: libDecodeHevc.so: cannot open shared object file: No such file or directory
> 
> I find libDecodeHevc.so file in "/root/miniconda/envs/clam/lib/python3.7/site-packages/sdpc/LINUX/libDecodeHevc.so", but I don't know why the system can't find file.

The complie file does not be added to some bash file. This may be helpful:https://blog.csdn.net/m0_72806612/article/details/143242378?spm=1001.2014.3001.5501
